package dev.launchforge.sdk;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.List;
import org.erdtman.jcs.JsonCanonicalizer;
import tools.jackson.databind.node.ArrayNode;
import tools.jackson.databind.node.ObjectNode;

final class GoldenVectorCorpus {
  private static final String FLAG_KEY = "rollout-flag";
  private static final String SALT = "stable_salt_1234";

  private GoldenVectorCorpus() {}

  static String generate() {
    ObjectNode corpus = SnapshotTestData.MAPPER.createObjectNode();
    corpus.put("corpusVersion", 1);
    corpus.put("schemaVersion", 1);
    corpus.put("algorithmVersion", 1);
    corpus.put(
        "generator",
        "GoldenVectorCorpus.java; SHA-256 outputs are generated by an independent reference function");
    corpus.set(
        "reasonCodes",
        SnapshotTestData.MAPPER.valueToTree(
            List.of(
                "FLAG_NOT_FOUND",
                "FLAG_DISABLED",
                "DEFAULT_VARIATION",
                "RULE_MATCH",
                "ROLLOUT_MATCH",
                "MISSING_ROLLOUT_KEY",
                "TYPE_MISMATCH",
                "INVALID_CONFIG",
                "SNAPSHOT_UNAVAILABLE",
                "ERROR_DEFAULT")));
    addRolloutVectors(corpus.putArray("rolloutVectors"));
    addOperatorCases(corpus.putArray("operatorCases"));
    ObjectNode snapshot = evaluationSnapshot();
    corpus.set("evaluationSnapshot", snapshot);
    addEvaluationCases(corpus.putArray("evaluationCases"));
    addMalformedSnapshots(corpus.putArray("malformedSnapshots"), snapshot);
    corpus.put("corpusChecksum", sha256(canonical(corpus.toString())));
    return canonical(corpus.toString()) + '\n';
  }

  private static void addRolloutVectors(ArrayNode vectors) {
    rolloutVector(vectors, "ascii", "checkout", SALT, "user-123");
    rolloutVector(vectors, "unicode", "unicode-flag", SALT, "Zoë-東京");
    rolloutVector(vectors, "signed-looking", "signed-flag", SALT, "-00042");
    rolloutVector(vectors, "line-break-subject", "line-break-flag", SALT, "line-one\nline-two");
    rolloutVector(vectors, "changed-salt", "unicode-flag", "changed_salt_1234", "Zoë-東京");
    String lowerBoundary = findSubject(49_999);
    String upperBoundary = findSubject(50_000);
    rolloutVector(vectors, "last-first-allocation-bucket", FLAG_KEY, SALT, lowerBoundary);
    rolloutVector(vectors, "first-second-allocation-bucket", FLAG_KEY, SALT, upperBoundary);

    ObjectNode sample = vectors.addObject();
    sample.put("name", "deterministic-ten-percent-sample");
    sample.put("flagKey", FLAG_KEY);
    sample.put("salt", SALT);
    sample.put("subjectPrefix", "sample-");
    sample.put("sampleSize", 10_000);
    sample.put("thresholdExclusive", 10_000);
    int selected = 0;
    for (int index = 0; index < 10_000; index++) {
      if (referenceBucket(FLAG_KEY, SALT, "sample-" + index) < 10_000) {
        selected++;
      }
    }
    sample.put("selectedCount", selected);
  }

  private static void rolloutVector(
      ArrayNode vectors, String name, String flagKey, String salt, String subject) {
    ObjectNode vector = vectors.addObject();
    vector.put("name", name);
    vector.put("flagKey", flagKey);
    vector.put("salt", salt);
    vector.put("subject", subject);
    vector.put("bucket", referenceBucket(flagKey, salt, subject));
  }

  private static void addOperatorCases(ArrayNode cases) {
    operator(cases, "equals", "string", "EQUALS", List.of("exact"), "exact", true);
    operator(cases, "not-equals", "string", "NOT_EQUALS", List.of("blocked"), "allowed", true);
    operator(cases, "in", "string", "IN", List.of("free", "pro"), "pro", true);
    operator(cases, "not-in", "string", "NOT_IN", List.of("blocked"), "pro", true);
    operator(cases, "starts-with", "string", "STARTS_WITH", List.of("pre"), "prefix", true);
    operator(cases, "ends-with", "string", "ENDS_WITH", List.of("fix"), "prefix", true);
    operator(cases, "contains-unicode", "string", "CONTAINS", List.of("é東"), "Aé東京", true);
    operator(cases, "empty-string", "string", "EQUALS", List.of(""), "", true);
    operator(cases, "number-eq", "number", "EQ", List.of(10), 10, true);
    operator(cases, "number-ne", "number", "NE", List.of(11), 10, true);
    operator(cases, "number-gt", "number", "GT", List.of(9), 10, true);
    operator(cases, "number-gte", "number", "GTE", List.of(10), 10, true);
    operator(cases, "number-lt", "number", "LT", List.of(11), 10, true);
    operator(cases, "number-lte", "number", "LTE", List.of(10), 10, true);
    operator(cases, "between-lower", "number", "BETWEEN_INCLUSIVE", List.of(10, 20), 10, true);
    operator(cases, "between-upper", "number", "BETWEEN_INCLUSIVE", List.of(10, 20), 20, true);
    operator(cases, "is-true", "boolean", "IS_TRUE", List.of(), true, true);
    operator(cases, "is-false", "boolean", "IS_FALSE", List.of(), false, true);
    operator(cases, "semver-eq-build", "semver", "SEMVER_EQ", List.of("1.2.3+a"), "1.2.3+b", true);
    operator(cases, "semver-gt", "semver", "SEMVER_GT", List.of("1.2.3-beta.2"), "1.2.3", true);
    operator(cases, "semver-gte", "semver", "SEMVER_GTE", List.of("2.0.0"), "2.0.0", true);
    operator(cases, "semver-lt", "semver", "SEMVER_LT", List.of("2.0.0"), "1.9.9", true);
    operator(cases, "semver-lte", "semver", "SEMVER_LTE", List.of("2.0.0"), "2.0.0", true);
    operator(cases, "exists", "string", "EXISTS", List.of(), "value", true);
    operator(cases, "not-exists", "string", "NOT_EXISTS", List.of(), null, true);
    operator(
        cases,
        "missing-negative-does-not-match",
        "string",
        "NOT_EQUALS",
        List.of("x"),
        null,
        false);
    operator(
        cases,
        "invalid-semver-does-not-match",
        "semver",
        "SEMVER_GT",
        List.of("1.0.0"),
        " 2.0.0 ",
        false);
  }

  private static void operator(
      ArrayNode cases,
      String name,
      String type,
      String operator,
      List<?> configured,
      Object contextValue,
      boolean expectedMatch) {
    ObjectNode item = cases.addObject();
    item.put("name", name);
    item.put("attributeType", type);
    item.put("operator", operator);
    item.set("configuredValues", SnapshotTestData.MAPPER.valueToTree(configured));
    item.put("contextPresent", contextValue != null);
    if (contextValue != null) {
      item.set("contextValue", SnapshotTestData.MAPPER.valueToTree(contextValue));
    }
    item.put("expectedMatch", expectedMatch);
  }

  private static ObjectNode evaluationSnapshot() {
    ObjectNode root = SnapshotTestData.root(42);
    ObjectNode flags = root.withObject("flags");
    flags.set("boolean-default", SnapshotTestData.booleanFlag(true, false, true));
    flags.set("disabled", SnapshotTestData.booleanFlag(false, false, true));
    flags.set("string-default", typedFlag("string", "safe", "hello"));
    flags.set("number-default", typedFlag("number", 0, 12.5));
    ObjectNode jsonFlag =
        typedFlag(
            "json",
            SnapshotTestData.MAPPER.createObjectNode(),
            SnapshotTestData.MAPPER.createObjectNode().put("theme", "forge").put("count", 2));
    flags.set("json-default", jsonFlag);
    ObjectNode ruled = SnapshotTestData.booleanFlag(true, false, true);
    ruled.put("defaultVariation", "off");
    SnapshotTestData.addRule(
        ruled,
        "unicode-rule",
        SnapshotTestData.condition(
            "name", "string", "EQUALS", SnapshotTestData.MAPPER.valueToTree("Zoë")),
        "on");
    flags.set("rule-flag", ruled);
    ObjectNode rolloutFlag = SnapshotTestData.booleanFlag(true, false, true);
    rolloutFlag.put("defaultVariation", "off");
    ObjectNode rollout = rolloutFlag.putObject("rollout");
    rollout.put("attribute", "userId");
    rollout.put("salt", SALT);
    rollout.putArray("weights").addObject().put("variation", "on").put("weight", 50_000);
    ((ArrayNode) rollout.get("weights")).addObject().put("variation", "off").put("weight", 50_000);
    flags.set(FLAG_KEY, rolloutFlag);
    return SnapshotTestData.copyOf(SnapshotTestData.canonicalSnapshot(root));
  }

  private static ObjectNode typedFlag(String type, Object off, Object on) {
    ObjectNode flag = SnapshotTestData.MAPPER.createObjectNode();
    flag.put("type", type);
    flag.put("enabled", true);
    flag.put("clientVisible", true);
    ArrayNode variations = flag.putArray("variations");
    variations.addObject().put("id", "off").set("value", SnapshotTestData.MAPPER.valueToTree(off));
    variations.addObject().put("id", "on").set("value", SnapshotTestData.MAPPER.valueToTree(on));
    flag.put("offVariation", "off");
    flag.put("defaultVariation", "on");
    flag.putArray("rules");
    return flag;
  }

  private static void addEvaluationCases(ArrayNode cases) {
    evaluation(
        cases,
        "flag-not-found",
        "missing",
        "boolean",
        false,
        null,
        false,
        "FLAG_NOT_FOUND",
        null,
        null);
    evaluation(
        cases,
        "type-mismatch",
        "boolean-default",
        "string",
        "fallback",
        null,
        "fallback",
        "TYPE_MISMATCH",
        null,
        null);
    evaluation(
        cases, "disabled", "disabled", "boolean", true, null, false, "FLAG_DISABLED", "off", null);
    evaluation(
        cases,
        "boolean-default",
        "boolean-default",
        "boolean",
        false,
        null,
        true,
        "DEFAULT_VARIATION",
        "on",
        null);
    evaluation(
        cases,
        "string-default",
        "string-default",
        "string",
        "fallback",
        null,
        "hello",
        "DEFAULT_VARIATION",
        "on",
        null);
    evaluation(
        cases,
        "number-default",
        "number-default",
        "number",
        -1,
        null,
        12.5,
        "DEFAULT_VARIATION",
        "on",
        null);
    evaluation(
        cases,
        "json-default",
        "json-default",
        "json",
        false,
        null,
        SnapshotTestData.MAPPER.createObjectNode().put("count", 2).put("theme", "forge"),
        "DEFAULT_VARIATION",
        "on",
        null);
    evaluation(
        cases,
        "unicode-rule",
        "rule-flag",
        "boolean",
        false,
        SnapshotTestData.MAPPER.createObjectNode().put("name", "Zoë"),
        true,
        "RULE_MATCH",
        "on",
        "unicode-rule");
    evaluation(
        cases,
        "missing-rollout-key",
        FLAG_KEY,
        "boolean",
        true,
        SnapshotTestData.MAPPER.createObjectNode(),
        false,
        "MISSING_ROLLOUT_KEY",
        "off",
        null);
    evaluation(
        cases,
        "empty-rollout-key",
        FLAG_KEY,
        "boolean",
        true,
        SnapshotTestData.MAPPER.createObjectNode().put("userId", ""),
        false,
        "MISSING_ROLLOUT_KEY",
        "off",
        null);
    String first = findSubject(49_999);
    evaluation(
        cases,
        "rollout-lower-boundary",
        FLAG_KEY,
        "boolean",
        false,
        SnapshotTestData.MAPPER.createObjectNode().put("userId", first),
        true,
        "ROLLOUT_MATCH",
        "on",
        null);
    String second = findSubject(50_000);
    evaluation(
        cases,
        "rollout-upper-boundary",
        FLAG_KEY,
        "boolean",
        true,
        SnapshotTestData.MAPPER.createObjectNode().put("userId", second),
        false,
        "ROLLOUT_MATCH",
        "off",
        null);
  }

  private static void evaluation(
      ArrayNode cases,
      String name,
      String flagKey,
      String requestedType,
      Object defaultValue,
      ObjectNode attributes,
      Object expectedValue,
      String reason,
      String variation,
      String rule) {
    ObjectNode item = cases.addObject();
    item.put("name", name);
    item.put("flagKey", flagKey);
    item.put("requestedType", requestedType);
    item.set("defaultValue", SnapshotTestData.MAPPER.valueToTree(defaultValue));
    item.put("contextKey", "subject-1");
    item.set(
        "attributes", attributes == null ? SnapshotTestData.MAPPER.createObjectNode() : attributes);
    ObjectNode expected = item.putObject("expected");
    expected.set("value", SnapshotTestData.MAPPER.valueToTree(expectedValue));
    expected.put("reason", reason);
    expected.put("revision", 42);
    if (variation != null) {
      expected.put("variation", variation);
    }
    if (rule != null) {
      expected.put("rule", rule);
    }
  }

  private static void addMalformedSnapshots(ArrayNode cases, ObjectNode valid) {
    ObjectNode unsupported = valid.deepCopy();
    unsupported.put("algorithmVersion", 2);
    malformed(cases, "unsupported-algorithm", SnapshotTestData.withRecomputedChecksum(unsupported));

    ObjectNode unsafe = SnapshotTestData.root(1);
    unsafe.withObject("flags").set("unsafe-number", typedFlag("number", 0, 9_007_199_254_740_992d));
    malformed(cases, "unsafe-integer", SnapshotTestData.withRecomputedChecksum(unsafe));

    ObjectNode invalidWeights = valid.deepCopy();
    ((ObjectNode)
            invalidWeights
                .withObject("flags")
                .withObject(FLAG_KEY)
                .withObject("rollout")
                .withArray("weights")
                .get(0))
        .put("weight", 49_999);
    malformed(
        cases, "invalid-rollout-total", SnapshotTestData.withRecomputedChecksum(invalidWeights));

    ObjectNode checksum = valid.deepCopy();
    checksum.put("revision", 99);
    malformed(cases, "checksum-mismatch", checksum.toString());
    malformed(cases, "duplicate-property", "{\"schemaVersion\":1,\"schemaVersion\":1}");
  }

  private static void malformed(ArrayNode cases, String name, String snapshot) {
    ObjectNode item = cases.addObject();
    item.put("name", name);
    item.put("snapshot", snapshot);
    item.put("expected", "REJECTED");
  }

  private static String findSubject(int target) {
    for (int candidate = 0; candidate < 2_000_000; candidate++) {
      String subject = "boundary-" + candidate;
      if (referenceBucket(FLAG_KEY, SALT, subject) == target) {
        return subject;
      }
    }
    throw new IllegalStateException("Reference generator did not find boundary subject");
  }

  private static int referenceBucket(String flagKey, String salt, String subject) {
    try {
      byte[] digest =
          MessageDigest.getInstance("SHA-256")
              .digest((flagKey + '\n' + salt + '\n' + subject).getBytes(StandardCharsets.UTF_8));
      long prefix = 0;
      for (int index = 0; index < 8; index++) {
        prefix = (prefix << 8) | Byte.toUnsignedLong(digest[index]);
      }
      return (int) Long.remainderUnsigned(prefix, 100_000);
    } catch (NoSuchAlgorithmException exception) {
      throw new IllegalStateException(exception);
    }
  }

  private static String canonical(String json) {
    try {
      return new JsonCanonicalizer(json).getEncodedString();
    } catch (IOException exception) {
      throw new IllegalStateException(exception);
    }
  }

  private static String sha256(String value) {
    try {
      return HexFormat.of()
          .formatHex(
              MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));
    } catch (NoSuchAlgorithmException exception) {
      throw new IllegalStateException(exception);
    }
  }
}
