package dev.launchforge.domain.organization;

public enum OrganizationAbility {
  VIEW_CONFIGURATION,
  EDIT_DRAFT,
  PUBLISH_NON_PRODUCTION,
  PUBLISH_PRODUCTION,
  MANAGE_MEMBERS,
  MANAGE_SDK_KEYS,
  MANAGE_AUDIT_RETENTION,
  DELETE_ORGANIZATION
}
